message(STATUS "")
message(STATUS "*************************************************************")
message(STATUS "")
message(STATUS "")
message(STATUS "If you are having problems with the CMake-based" )
message(STATUS "build system, create an environment variable named")
message(STATUS "\"DEBUG\".  The value does not matter. This will")
message(STATUS "cause the build system and associated test scripts")
message(STATUS "to print debugging logs.")
message(STATUS "")
message(STATUS "")
message(STATUS "Debug logging was done in this manner because the CMake")
message(STATUS "build system test scripts run on each invocation of CMake,")
message(STATUS "the logic being that if the CMake scripts we need don't work,")
message(STATUS "there is no point on continuing further until they are fixed.")
message(STATUS "Some of these tests execute CMake again in another process")
message(STATUS "to test scripts in isolation. Because of this, it was decided,")
message(STATUS "in order to leave the console clear for build system messages,")
message(STATUS "to not hardcode in the CMake CLI option to set the build type")
message(STATUS "to DEBUG mode and to instead rely on an environment variable.")
message(STATUS "")
message(STATUS "")
message(STATUS "*************************************************************")
message(STATUS "")
